#%RAML 1.0 SecurityScheme
type: x-clientsecret
displayName: Client ID & Client Secret Authentication scheme
description: |
  This security scheme validates requests to the API using client ID and client Secret provided in the request header.
describedBy: 
  queryParameters: 
    client_id:
      type: string
    client_secret:
      type: string
  