#%RAML 1.0 NamedExample


 {
    "valPractSCResult": {
      "o_LicDesigSamp": "",
      "o_CustPractId": "",
      "o_CustMatchType": "",
      "o_ProfDesigMatched": "",
      "o_CustMedproId": "",
      "o_ZipMatch": "",
      "o_CustMeNum": "",
      "o_CustDeaNum": "",
      "o_CustPhoneNumber": "",
      "o_MatchMethod": "",
      "o_CustBypassAddrBlock": "",
      "o_ReasonMsg": "",
      "o_StateGracePeriod": "",
      "o_MedproId": "",
      "o_CustAddrLine1": "",
      "o_OverallSampCentral": "",
      "o_CustMiddleInit": "",
      "o_ProfDesigEligibility": "",
      "o_SanctionSamp": "",
      "o_OverallAddrEligibility": "",
      "o_MatchRule": "",
      "o_AddressMatch": "",
      "o_LicExpiredOverallSamp": "",
      "o_CustStateLicNum": "",
      "o_CustZip": "",
      "o_CustLicStateId": "",
      "o_CustAddrLine3": "",
      "o_LicExpDate": "",
      "o_CustFirstName": "",
      "o_CustNpiNum": "",
      "o_CustProfDesig": "",
      "o_OverallSampleability": "",
      "o_CustCity": "",
      "o_LicStatusDescr": "",
      "o_ProfDesigMapped": "",
      "o_CustAddrLine2": "",
      "o_CustLastName": "",
      "o_CustStateId": "",
      "o_RecvdInLast12Mos": "",
      "o_CustGracePeriod": "",
      "o_AddressTypeIncl": "",
      "o_RecvdExpiredSamp": "",
      "o_LicStatusSamp": "",
      "o_AddrSource": "",
      "o_CurrAddrMatch": "",
      "o_CustSuffixName": "",
      "o_CustAddrRdi": ""
    }
  }
