#%RAML 1.0 NamedExample


{
  "v_LicStateId": "",
  "v_StateLicNum": "",
  "v_DeaNum": "",
  "v_MeNum": "",
  "v_NpiNum": "",
  "v_MedproId": "",
  "v_LastName": "",
  "v_FirstName": "",
  "v_Middle": "",
  "v_Suffix": "",
  "v_ProfDesig": "",
  "v_AddrLine1": "",
  "v_AddrLine2": "",
  "v_AddrLine3": "",
  "v_City": "",
  "v_State": "",
  "v_Zip": "",
  "v_PhoneNumber": "",
  "v_CustPractNum": "",
  "v_BypassAddressBlock": "",
  "v_MatchType": "",
  "v_UserName": "",
  "v_Password": ""
}