#%RAML 1.0 DocumentationItem
title: FAQs
content: |
  1. How do I access this API ? 
      Refer to Getting started page where URIs for both mock and actual implementations are provided.
  2. Whom to contact when API is inaccessible? 
      Contact API Management team (mail id - INCHAPIPlatformTeam@astrazeneca.com)
  3. How to add a new functionality to this API? 
      Contact API Management team (mail id - INCHAPIPlatformTeam@astrazeneca.com)
      