#%RAML 1.0 DocumentationItem
title: Getting Started
content: |
  - API Prerequisites: 
    Mock URI: https://anypoint.mulesoft.com/mocking/api/v1/links/46f051b7-6b3a-4a6f-964b-442259a72e1a/api/v1/validates/practitioners
  - Accessing API: https://eu-nprd.connect.astrazeneca.com/sys-employee-api-sit/api/v1/employees/authentications/users?employeeID=kpxs536&systemcode=PRID
