#%RAML 1.0 DocumentationItem
title: Support
content: |
  - API Owner: AZ API Platform Support Group
  - OSM : Madan Ilangovan
  - CSM : Madan Ilangovan
  - SNOW Support Group: AZ API Platform Support Group
  - Email DL: INCHAPIPlatformTeam@astrazeneca.com

